spring:
    datasource:
        continue-on-error: false
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-active: 501
        max-wait: 60000
        min-evictable-idle-time-millis: 1800000
        min-idle: 5
        password: 123456
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 300000
        url: jdbc:mysql://192.168.150.120:3306/ershou?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        validation-query: SELECT 1 FROM DUAL
    devtools:
        restart:
            enabled: true
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
ylrc:
    database:
        backup:
            database:
                name: db_boot_base
            dir: ''
            password: orcl
            username: root
    upload:
        photo:
            maxsize: 1024
            path: ''
            sufix: .jpg,.png,.gif,.jpeg
